version: "3.3"
services:
    angular:
        hostname : localhost
        build: ./client
        ports: 
            - "80:80"
        networks:
            - compose-networks

    node-test:
        build: ./server
        ports:
            - "3001:3001"
        networks: 
            - compose-networks
    
    mongodb:
        image: "mongo"
        ports:
            - "27017:27017"
        networks:
            - compose-networks
        
networks:
    compose-networks:
